### ISSUE TITLE
Django AttributeError

### ISSUE THREAD

**Issue by rockwotj** [google/apis-client-generator#14]
Just ran `pip install google-apis-client-generator` then tried to run a couple commands for the generate_library command and got this traceback every time. Any suggestions?

```
Traceback (most recent call last):
  File "/usr/local/bin/generate_library", line 9, in <module>
    load_entry_point('google-apis-client-generator==1.4.2', 'console_scripts', 'generate_library')()
  File "/Library/Python/2.7/site-packages/googleapis/codegen/script_stubs.py", line 9, in RunGenerateLibrary
    from googleapis.codegen import generate_library
  File "/Library/Python/2.7/site-packages/googleapis/codegen/generate_library.py", line 35, in <module>
    from googleapis.codegen import generator_lookup
  File "/Library/Python/2.7/site-packages/googleapis/codegen/generator_lookup.py", line 10, in <module>
    from googleapis.codegen import csharp_generator
  File "/Library/Python/2.7/site-packages/googleapis/codegen/csharp_generator.py", line 23, in <module>
    from googleapis.codegen import api
  File "/Library/Python/2.7/site-packages/googleapis/codegen/api.py", line 39, in <module>
    from googleapis.codegen import data_types
  File "/Library/Python/2.7/site-packages/googleapis/codegen/data_types.py", line 24, in <module>
    from googleapis.codegen import template_objects
  File "/Library/Python/2.7/site-packages/googleapis/codegen/template_objects.py", line 27, in <module>
    from googleapis.codegen.django_helpers import MarkSafe
  File "/Library/Python/2.7/site-packages/googleapis/codegen/django_helpers.py", line 50, in <module>
    django_template.add_to_builtins(
AttributeError: 'module' object has no attribute 'add_to_builtins'
```

**Comment by aiuto** [comment]
Downgrade django to 1.7.  See https://github.com/google/apis-client-generator/issues/13

**Comment by rockwotj** [comment]
Thanks.
