### ISSUE TITLE
Generating c++ fails.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [google/apis-client-generator#25]
```
rennie@rennie:~/gitrepos/google-api-cpp-client$ virtualenv env
New python executable in /usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/bin/python
Installing setuptools, pip, wheel...done.
rennie@rennie:~/gitrepos/google-api-cpp-client$ env/bin/pip install google-apis-client-generator
Collecting google-apis-client-generator
/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading google-apis-client-generator-1.4.2.tar.gz (279kB)
    100% |████████████████████████████████| 286kB 3.1MB/s 
[?25hCollecting django (from google-apis-client-generator)
  Downloading Django-1.11.1-py2.py3-none-any.whl (6.9MB)
    100% |████████████████████████████████| 7.0MB 258kB/s 
[?25hCollecting httplib2 (from google-apis-client-generator)
  Downloading httplib2-0.10.3.tar.gz (204kB)
    100% |████████████████████████████████| 204kB 6.1MB/s 
[?25hCollecting google-apputils (from google-apis-client-generator)
  Downloading google-apputils-0.4.2.zip (101kB)
    100% |████████████████████████████████| 102kB 12.9MB/s 
[?25hCollecting python-gflags (from google-apis-client-generator)
  Downloading python-gflags-3.1.1.tar.gz (52kB)
    100% |████████████████████████████████| 61kB 13.9MB/s 
[?25hCollecting google-api-python-client (from google-apis-client-generator)
  Downloading google_api_python_client-1.6.2-py2.py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 14.3MB/s 
[?25hCollecting pytz (from django->google-apis-client-generator)
  Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
    100% |████████████████████████████████| 491kB 3.4MB/s 
[?25hCollecting python-dateutil>=1.4 (from google-apputils->google-apis-client-generator)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 7.5MB/s 
[?25hRequirement already satisfied: six<2dev,>=1.6.1 in ./env/lib/python2.7/site-packages (from google-api-python-client->google-apis-client-generator)
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client->google-apis-client-generator)
  Downloading uritemplate-3.0.0-py2.py3-none-any.whl
Collecting oauth2client<5.0.0dev,>=1.5.0 (from google-api-python-client->google-apis-client-generator)
  Downloading oauth2client-4.0.0-py2.py3-none-any.whl (184kB)
    100% |████████████████████████████████| 194kB 5.7MB/s 
[?25hCollecting rsa>=3.1.4 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->google-apis-client-generator)
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->google-apis-client-generator)
  Using cached pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client->google-apis-client-generator)
  Downloading pyasn1-0.2.3-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 14.1MB/s 
[?25hBuilding wheels for collected packages: google-apis-client-generator, httplib2, google-apputils, python-gflags
  Running setup.py bdist_wheel for google-apis-client-generator ... [?25ldone
[?25h  Stored in directory: /usr/local/google/home/rennie/.cache/pip/wheels/2d/08/6a/6b15dc90651bcca2d09abf126041d128f8a591b6e21d4eb656
  Running setup.py bdist_wheel for httplib2 ... [?25ldone
[?25h  Stored in directory: /usr/local/google/home/rennie/.cache/pip/wheels/ca/ac/5f/749651f7925b231103f5316cacca82a487810c22d30f011c0c
  Running setup.py bdist_wheel for google-apputils ... [?25ldone
[?25h  Stored in directory: /usr/local/google/home/rennie/.cache/pip/wheels/c2/c7/36/083b74a76ab1eeea8ebeb52c0ab118d455caec0607699c0eb8
  Running setup.py bdist_wheel for python-gflags ... [?25ldone
[?25h  Stored in directory: /usr/local/google/home/rennie/.cache/pip/wheels/f8/d5/b7/0647704d6fdd87819ff64008f883ff857c8340c6b122c17549
Successfully built google-apis-client-generator httplib2 google-apputils python-gflags
Installing collected packages: pytz, django, httplib2, python-dateutil, python-gflags, google-apputils, uritemplate, pyasn1, rsa, pyasn1-modules, oauth2client, google-api-python-client, google-apis-client-generator
Successfully installed django-1.11.1 google-api-python-client-1.6.2 google-apis-client-generator-1.4.2 google-apputils-0.4.2 httplib2-0.10.3 oauth2client-4.0.0 pyasn1-0.2.3 pyasn1-modules-0.0.8 python-dateutil-2.6.0 python-gflags-3.1.1 pytz-2017.2 rsa-3.4.2 uritemplate-3.0.0
rennie@rennie:~/gitrepos/google-api-cpp-client$ ls env/bin
activate          easy_install-2.7  pyrsa-decrypt          python
activate.csh      expand_templates  pyrsa-decrypt-bigfile  python2
activate.fish     generate_library  pyrsa-encrypt          python2.7
activate_this.py  gflags2man.py     pyrsa-encrypt-bigfile  python-config
django-admin      gflags2man.pyc    pyrsa-keygen           wheel
django-admin.py   pip               pyrsa-priv2pub
django-admin.pyc  pip2              pyrsa-sign
easy_install      pip2.7            pyrsa-verify
rennie@rennie:~/gitrepos/google-api-cpp-client$ ls
build           doxygenate.py   external_dependencies    README.txt
CMakeLists.txt  doxygen.config  introspect.cmake         service_apis
COPYING.txt     env             prepare_dependencies.py  src
rennie@rennie:~/gitrepos/google-api-cpp-client$ cd service_apis/
rennie@rennie:~/gitrepos/google-api-cpp-client/service_apis$ ls
calendar  CMakeLists.txt  drive  youtube
rennie@rennie:~/gitrepos/google-api-cpp-client/service_apis$ cd calendar/
rennie@rennie:~/gitrepos/google-api-cpp-client/service_apis/calendar$ ls
CMakeLists.txt  descriptor.json  google  LICENSE.txt  readme.html
rennie@rennie:~/gitrepos/google-api-cpp-client/service_apis/calendar$ ../../env/bin/generate_library --input=descriptor.json --language=cpp --output_dir=/tmp/generated
Traceback (most recent call last):
  File "../../env/bin/generate_library", line 11, in <module>
    sys.exit(RunGenerateLibrary())
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/script_stubs.py", line 9, in RunGenerateLibrary
    from googleapis.codegen import generate_library
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/generate_library.py", line 35, in <module>
    from googleapis.codegen import generator_lookup
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/generator_lookup.py", line 10, in <module>
    from googleapis.codegen import csharp_generator
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/csharp_generator.py", line 23, in <module>
    from googleapis.codegen import api
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/api.py", line 39, in <module>
    from googleapis.codegen import data_types
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/data_types.py", line 24, in <module>
    from googleapis.codegen import template_objects
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/template_objects.py", line 27, in <module>
    from googleapis.codegen.django_helpers import MarkSafe
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/django_helpers.py", line 50, in <module>
    django_template.add_to_builtins(
AttributeError: 'module' object has no attribute 'add_to_builtins'
rennie@rennie:~/gitrepos/google-api-cpp-client/service_apis/calendar$ ../../env/bin/generate_library --input=descriptor.json --language=c++ --output_dir=/tmp/generated
Traceback (most recent call last):
  File "../../env/bin/generate_library", line 11, in <module>
    sys.exit(RunGenerateLibrary())
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/script_stubs.py", line 9, in RunGenerateLibrary
    from googleapis.codegen import generate_library
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/generate_library.py", line 35, in <module>
    from googleapis.codegen import generator_lookup
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/generator_lookup.py", line 10, in <module>
    from googleapis.codegen import csharp_generator
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/csharp_generator.py", line 23, in <module>
    from googleapis.codegen import api
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/api.py", line 39, in <module>
    from googleapis.codegen import data_types
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/data_types.py", line 24, in <module>
    from googleapis.codegen import template_objects
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/template_objects.py", line 27, in <module>
    from googleapis.codegen.django_helpers import MarkSafe
  File "/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/env/local/lib/python2.7/site-packages/googleapis/codegen/django_helpers.py", line 50, in <module>
    django_template.add_to_builtins(
AttributeError: 'module' object has no attribute 'add_to_builtins'
rennie@rennie:~/gitrepos/google-api-cpp-client/service_apis/calendar$ 

```

**Comment by SurferJeffAtGoogle** [comment]
This doesn't occur if I run apis-client-generator from source, so I guess it's just time to republish to pip?

**Comment by SurferJeffAtGoogle** [comment]
Fixed.
