### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/apis-client-generator#4]
```
Hello,

I'm trying to execute the generator for the new Admin-SDK API, however I'm not 
even able to download plus API

What steps will reproduce the problem?

$ python $(/bin/pwd)/googleapis/codegen/generate_library.py --api_name=plus 
--api_version=v1 --language=java --output_dir=/tmp/gen --language=java
Traceback (most recent call last):
  File "/Users/alejacquet/Development/git/google-apis-client-generator/src/googleapis/codegen/generate_library.py", line 245, in <module>
    app.run()
  File "/Library/Python/2.7/site-packages/google_apputils-0.3.0-py2.7.egg/google/apputils/app.py", line 216, in run
    return _actual_start()
  File "/Library/Python/2.7/site-packages/google_apputils-0.3.0-py2.7.egg/google/apputils/app.py", line 244, in _actual_start
    really_start()
  File "/Library/Python/2.7/site-packages/google_apputils-0.3.0-py2.7.egg/google/apputils/app.py", line 203, in really_start
    sys.exit(main(argv))
  File "/Users/alejacquet/Development/git/google-apis-client-generator/src/googleapis/codegen/generate_library.py", line 152, in main
    language_variant=FLAGS.language_variant)
  File "/Users/alejacquet/Development/git/google-apis-client-generator/src/googleapis/codegen/generate_library.py", line 179, in Generate
    language_variations = Targets().VariationsForLanguage(language)
  File "/Users/alejacquet/Development/git/google-apis-client-generator/src/googleapis/codegen/targets.py", line 68, in __init__
    files.GetFileContents(self.targets_path))
  File "/Users/alejacquet/Development/git/google-apis-client-generator/src/googleapis/codegen/json_with_comments.py", line 54, in Loads
    return json.loads(stripped, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 326, in loads
    
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
ValueError: Expecting property name: line 9 column 9 (char 198)



What is the expected output? What do you see instead?
Export the api

What version of the product are you using? On what operating system?
MacOSX 10.8.3 and Ubuntu 13.04 I've tried with python2.6 and python2.7

Please provide any additional information below.


```

Original issue reported on code.google.com by `alejacq...@gmail.com` on 21 May 2013 at 7:09

**Comment by aiuto** [comment]
obsolete. two years of changes have happened since then.
