### ISSUE TITLE
Support for python3

### ISSUE THREAD

**Issue by KishoreNamala** [google/apis-client-generator#47]
Hi,

Is there a timeline on when python3 will be supported here ? We are trying to generate a client for the GCP Marketplace procurement APIs as mentioned [here](https://github.com/googlecodelabs/gcp-marketplace-integrated-saas/blob/master/java/README.md) and are running into the below error.

`generate_library --input=discovery.json --language=java --output_dir=procurement
Traceback (most recent call last):
  File "/usr/local/google/home/kishorenamala/.local/bin/generate_library", line 5, in <module>
    from googleapis.codegen.script_stubs import RunGenerateLibrary
  File "/usr/local/google/home/kishorenamala/.local/lib/python3.9/site-packages/googleapis/codegen/script_stubs.py", line 4, in <module>
    from google.apputils import run_script_module
  File "/usr/local/google/home/kishorenamala/.local/lib/python3.9/site-packages/google/apputils/run_script_module.py", line 122
    print 'Stub script %s (auto-generated). Options:' % sys.argv[0]
          ^
SyntaxError: invalid syntax
`

**Comment by chingor13** [comment]
Unfortunately, we don't have a timeline on migrating this generator to python 3. In fact, this repository contains a very old version of the generator (we will likely be archiving this repository and redirecting to other places).

We do have [a convenience script written](https://github.com/googleapis/google-api-java-client-services/blob/master/generator/generate.sh) that uses the most up to date templates for generating the Java client, but it still requires python 2.

**Comment by Robert-Aron293** [comment]
Hello,

Where can I find a newer version of this generator?

**Comment by KishoreNamala** [comment]
The script mentioned by @chingor13 is the only way it is working now and it needs python2

**Comment by Robert-Aron293** [comment]
Yes, but that script is only for Java.

**Comment by chlebnymaciej** [comment]
There is solution for generating libraries from this app despite not supporting python3.  You must run this app from docker level
```
 docker run -it python:2.7 bash
```
In this image pip does not make any problems with installing and running generator.
