### ISSUE TITLE
cannot import name cpp_import_manager

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/apis-client-generator#6]
```
It seems that cpp_import_manager.py is missing from the source tree.

hyrule:~ protomouse$ generate_library 
Traceback (most recent call last):
  File "/usr/local/bin/generate_library", line 8, in <module>
    load_entry_point('google-apis-client-generator==1.4.2', 'console_scripts', 'generate_library')()
  File "/Library/Python/2.7/site-packages/google_apis_client_generator-1.4.2-py2.7.egg/googleapis/codegen/script_stubs.py", line 9, in RunGenerateLibrary
    from googleapis.codegen import generate_library
  File "/Library/Python/2.7/site-packages/google_apis_client_generator-1.4.2-py2.7.egg/googleapis/codegen/generate_library.py", line 35, in <module>
    from googleapis.codegen import generator_lookup
  File "/Library/Python/2.7/site-packages/google_apis_client_generator-1.4.2-py2.7.egg/googleapis/codegen/generator_lookup.py", line 10, in <module>
    from googleapis.codegen import cpp_generator
  File "/Library/Python/2.7/site-packages/google_apis_client_generator-1.4.2-py2.7.egg/googleapis/codegen/cpp_generator.py", line 27, in <module>
    from googleapis.codegen import cpp_import_manager
ImportError: cannot import name cpp_import_manager
```

Original issue reported on code.google.com by `martin.h...@minmb.se` on 18 Feb 2014 at 9:02

**Comment by aiuto** [comment]
Code was added.
